package fun.ogtimes.skywars.spigot.config;

import fun.ogtimes.skywars.spigot.SkyWars;
import fun.ogtimes.skywars.spigot.utils.Utils;
import com.google.common.collect.Lists;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class ConfigManager {
    public static SkyConfiguration main;
    public static SkyConfiguration score;
    public static SkyConfiguration abilities;
    public static SkyConfiguration shop;
    public static SkyConfiguration signs;
    public static SkyConfiguration database;

    public static void mainConfig() {
        File var0 = new File(SkyWars.getPlugin().getDataFolder(), "config.yml");
        main = new SkyConfiguration(var0);
        main.setHeader("-------------------------------- #", "", "SKYWARS", "By CookLoco and the OGTimes Development Team", "Battle with players in the sky", "", "-------------------------------- #");
        main.addDefault("check_updates", true, "Check if exists a new update (RECOMMENDED YOU LEAVE TRUE)");
        main.addDefault("debug", false, "Debug mode", "enable if you have some crash/error and create an issue at our GitHub repository.");
        main.addDefault("debug-database", false, "Debug database (MySQL)", "enable if you have some crash/error and create an issue at our GitHub repository.");
        main.addDefault("locale", "en", "Available languages:", "      en: English (Default)", "      es: Spanish", "      nl: Dutch");
        main.addDefault("kitmenu_rows", 3, "Rows/Lines from the Kit Menu (WAITING GAME)");
        main.addDefault("kit_permission", false, "If is true, players with the permission (skywars.kit.KitName) can buy this kit");
        main.addDefault("maxtime", 1200, "Maximum time for every arena/game");
        main.addDefault("spawn", "", "Lobby coords [MultiArena/Lobby]", "type /sw lobbyspawn to set the Lobby Spawn");
        ArrayList var1 = new ArrayList();
        var1.add("Lobby");
        main.addDefault("lobbies_servers", var1, "Lobby server list for random tp (BUNGEECORD SERVERS)");
        main.addDefault("max_items_types_chest", 15, "max slots used per generated chest (IN GAME)");
        main.addDefault("economy.mode",
                "Custom",
                "Economy types:",
                "    Custom: included per default in SkyWars (RECOMMENDED)",
                "    Vault: hook with Vault and other plugin like Essentials or iConomy");
        main.addDefault("economy.craftconomy3_currency", "Dollar", "Currency set when you has been configured CraftConomy3 (Default: Dollar)");
        main.addDefault("reward.death", 1, "reward that receive every survivor when a player die");
        main.addDefault("reward.kill", 2, "reward for kill some player");
        main.addDefault("reward.win", 10, "reward for winner");
        main.addDefault("reward.wincmd.enabled", false, "Enable or disable winner commands (EXECUTED BY CONSOLE)");
        ArrayList var2 = new ArrayList();
        var2.add("20/money give %winner% 20");
        var2.add("100/say %winner% won a game!");
        main.addDefault("reward.wincmd.list", var2, "Commands list (VARIABLES: %winner% , %map%)", "\tFORMAT: 'CHANCE/CMD'", "\tExample: 90/give %winner% minecraft:diamond_block 1", "\tCHANCE: 0-100");
        main.addDefault("item.kits", "1 PAPER", "Items in waiting Lobby, for message and translation go to the item section in messages files", "Format:   SLOT ITEM_NAME", "SLOT From 1 to 9 (hotbar)", "If you want to edit Shop item in Lobby go to shop.yml");
        main.addDefault("item.settings", "2 DIAMOND");
        main.addDefault("item.vote", "3 EMPTY_MAP");
        main.addDefault("item.exit", "9 BED");
        main.addDefault("menu.kits", null, "Kit Selector menu options");
        main.addDefault("menu.kits.unavailable.enabled", false, "Enable or disable if should replace unavailable kit icon for some item (Default: false)");
        main.addDefault("menu.kits.unavailable.item", "STAINED_GLASS_PANE:14", "ITEM_NAME:DATA");
        main.addDefault("mode.plugin", "MultiArena", "Plugin Modes:", "      BungeeMode: Only one game per server (better performance)", "      MultiArena: Unlimited games per server (underperforming with many games)", "      Lobby: Only Lobby System for Bungee Servers (before SkyWarsLobby)");
        main.addDefault("mode.bungee-autostart", true, "Auto Start when a game ends (BungeeMode)");
        main.addDefault("mode.bungeerandom", true, "Select a random map from configured arenas");
        main.addDefault("mode.bungeemapset", "default", "Select the same map all the time (BUNGEERANDOM MUST BE FALSE)");
        main.addDefault("server", "", "BungeeMode setting for Sign System (MySQL REQUIRED)", "enabled by default if the server is in BungeeMode, You will need a Lobby server", "with SkyWars in Lobby mode for the Sign System (MySQL REQUIRED IN BOTH SERVERS)");
        main.addDefault("data.type", "SQLite", "Types:", "    SQLite: Local File (Default)", "    MySQL: MySQL Server required");
        main.addDefault("data.mysql.server", "localhost", "MySQL server address/ip");
        main.addDefault("data.mysql.db", "SkyWars", "database name");
        main.addDefault("data.mysql.user", "root", "MySQL User");
        main.addDefault("data.mysql.port", 3306, "MySQL Port");
        main.addDefault("data.mysql.password", "password", "MySQL password");
        main.addDefault("data.mysql.tablename.data", "SkyWars_Data", "Table name of player data");
        main.addDefault("data.mysql.tablename.economy", "SkyWars_Economy", "Table name of custom economy data");
        main.addDefault("data.mysql.tablename.servers", "SkyWars_Servers", "Table name of servers info");
        main.addDefault("options.weather", false, "enable or disable weather in arena worlds");
        main.addDefault("options.creaturespawn", false, "enable or disable mobs spawn in arena worlds");
        main.addDefault("options.saveInventory", true, "save inventory when player join to the game and restored when leave");
        main.addDefault("options.forceLobbySpawn", true, "force teleport to spawn when a player join");
        main.addDefault("options.orderedSpawnPoints", true, "sequencial spawn points in arena");
        main.addDefault("options.disablePvP-Outside-The-Arena", false, "disable pvp in Lobby world");
        main.addDefault("options.disableDamage-Outside-The-Arena", false, "disable all damage in Lobby");
        main.addDefault("options.leaveMessage", false, "enable or disable leave message when player leave from the server");
        main.addDefault("options.joinMessage", false, "enable or disable join message when player join to the server");
        main.addDefault("options.disableLeaveItem", false, "disable leave item (bed)");
        main.addDefault("options.disablePerWorldTab", false, "disable separated Tab per world (RECOMMEND YOU LEAVE FALSE FOR 1.8 & 1.9 SERVERS)");
        main.addDefault("options.disablePerWorldChat", false, "disable separated chat per world");
        main.addDefault("options.disableSpectatorMode-Death", false, "disable spectator mode when player die");
        main.addDefault("options.removeAllCageOnStart", true, "true: remove all cage, false: remove cage's floor");
        main.addDefault("options.perWorldTabBypass", false, "Enable or disable perWorldTab for players with the permisison: skywars.tab.bypass");
        main.addDefault("options.combatLogTime", 3, "The time in seconds that CombatLog will act after a player takes damage from another", "Default: 3");
        ArrayList var3 = new ArrayList();
        var3.add("help");
        var3.add("spawn");
        var3.add("home");
        main.addDefault("block.commands.mode", "blacklist", "Available modes:", "      blacklist: block all commands in the list", "      whitelist: only allow commands in the list");
        main.addDefault("block.commands.ingame", var3, "Commands blocked for players in game (in arena)");
        main.options().copyDefaults(true);
        main.getEConfig().setNewLinePerKey(true);
        main.save();
    }

    public static void scoreboardConfig() {
        File var0 = new File(SkyWars.getPlugin().getDataFolder(), "scoreboard.yml");
        score = new SkyConfiguration(var0);
        score.setHeader("VARIABLES:", "    - Player name:         " + "%PLAYER%, %USERNAME%".toLowerCase(), "    - Player Coins:        " + "%COINS%, %POINTS%".toLowerCase(), "    - Player Deaths:       " + "%SW-DEATHS%, %SW-D%, %STATS-DEATHS%".toLowerCase(), "    - Player Kills:        " + "%SW-KILLS%, %SW-K%, %STATS-KILLS%".toLowerCase(), "    - Player Wins:         " + "%SW-WINS%, %SW-W%, %STATS-WINS%".toLowerCase(), "    - Games Played:        " + "%SW-PLAYED%, %SW-P%, %STATS-PLAYED%".toLowerCase(), "    - Arrow Shot:          " + "%SW-ARROW-SHOT%, %SW-AS%, %STATS-ARROW-SHOT%".toLowerCase(), "    - Arrow Hit:           " + "%SW-ARROW-HIT%, %SW-AH%, %STATS-ARROW-HIT%".toLowerCase(), "    - Blocks Broken:       " + "%SW-BLOCKS-BROKEN%, %SW-BB%, %STATS-BLOCKS-BROKEN%".toLowerCase(), "    - Block Placed:        " + "%SW-BLOCKS-PLACED%, %SW-BP%, %STATS-BLOCKS-PLACED%".toLowerCase(), "    - Distance Walked:     " + "%SW-DISTANCE-WALKED%, %SW-DW%, %STATS-DISTANCE-WALKED%".toLowerCase(), "    - Time Played:         " + "%SW-TIME-PLAYED%, %SW-TP%, %STATS-TIME-PLAYED%".toLowerCase(), "    - Kill/Death Ratio:    " + "%SW-KILLS-DEATHS%, %SW-KDR%".toLowerCase(), "    - Selected Glass:      " + "%GLASS%".toLowerCase(), "SCOREBOARD VARIABLES:", "    - Empty line:          %empty%", "GAME SCOREBOARD VARIABLES:", "    - Arena Name:          " + "%ARENA-NAME%, %A-NAME%".toLowerCase(), "    - Arena Max Players:   " + "%ARENA-MAX-PLAYERS%, %A-MAX-P%".toLowerCase(), "    - Players in Arena:    " + "%ARENA-INGAME-PLAYERS%, %A-INGAME-P%".toLowerCase(), "    - Current event title: " + "%ARENA-EVENT-TITLE% %A-EVENT-TITLE%".toLowerCase(), "    - Current event time:  " + "%ARENA-EVENT-TIME% %A-EVENT-TIME%".toLowerCase(), "    - Current kill streak: " + "%SW-KILL-STREAK% %SW-KS%".toLowerCase(), "SCOREBOARD CONDITIONALS:", "    <a-events> Check if the arena has events enabled", "    <a-ingame> Check if the arena is in game");
        score.addDefault("lobby.enabled", true, "Enable or disable Lobby Scoreboard");
        ArrayList var1 = new ArrayList();
        var1.add("test1");
        var1.add("test2");
        score.addDefault("lobby.disabledWorlds", var1, "Lobby Scoreboard blacklist (Disabled worlds)");
        score.addDefault("lobby.title", "&e&lSkyWars", "Lobby Scoreboard title");
        ArrayList var2 = new ArrayList();
        var2.add("&5Coins:");
        var2.add("&a%coins%");
        var2.add("%empty%");
        var2.add("&6Server Name");
        score.addDefault("lobby.lines", var2, "Lobby Scoreboard lines (Max: 16)");
        score.addDefault("game.title", "&e&lSkyWars", "Game Scoreboard title");
        ArrayList var3 = new ArrayList();
        var3.add("<a-ingame><a-events>&5%a-event-title% in:");
        var3.add("<a-ingame><a-events>&a%a-event-time%");
        var3.add("<a-ingame><a-events>%empty%");
        var3.add("&5Map:");
        var3.add("&a%a-name%");
        var3.add("%empty%");
        var3.add("&5Players:");
        var3.add("&a%a-ingame-p%/%a-max-p%");
        var3.add("%empty%");
        var3.add("&6Server Name");
        score.addDefault("game.lines", var3, "Game Scoreboard lines (Max: 16)");
        ArrayList var4 = new ArrayList();
        score.addDefault("hologram.locations", var4, "Holographics Coords");
        ArrayList var5 = new ArrayList();
        var5.add("&a%PLAYER%'s &7&k&l||&3&lSkyWars&7&k&l||I&astatistics");
        var5.add("&aWins&7: &6%sw-w%");
        var5.add("&aKills&7: &6%sw-k%");
        var5.add("&aDeaths&7: &6%sw-d%");
        var5.add("&aGames played&7: &6%sw-p%");
        var5.add("&aArrows shot&7: &6%sw-as%");
        var5.add("&aArrows hit&7: &6%sw-ah%");
        var5.add("&aBlocks broken&7: &6%sw-bb%");
        var5.add("&aBlocks placed&7: &6%sw-bp%");
        var5.add("&aDistance walked&7: &6%sw-dw%");
        var5.add("&aTime played&7: &6%sw-tp%");
        score.addDefault("hologram.lines", var5, "Holographics Lines");
        score.options().copyDefaults(true);
        score.getEConfig().setNewLinePerKey(true);
        score.save();
    }

    public static void abilitiesConfig() {
        File var0 = new File(SkyWars.getPlugin().getDataFolder(), "abilities.yml");
        abilities = new SkyConfiguration(var0);
        ArrayList var2 = new ArrayList();
        abilities.addDefault("enabled", true, "enable or disable abilities on the server");
        abilities.addDefault("configVersion", 2, "Don't edit this value");
        abilities.addDefault("menu.lore.price", "&6Price: %price% points");
        abilities.addDefault("menu.lore.disabled", "&8&lDISABLED");
        abilities.addDefault("menu.lore.clickto.enable", "&6Click to enable", "Click ability icon to enable");
        abilities.addDefault("menu.lore.clickto.disable", "&6Click to disable", "Click ability icon to disable");
        abilities.addDefault("menu.lore.status.purchase", "&6Click to purchase this ability upgrade!", "Level item lore status");
        abilities.addDefault("menu.lore.status.afford", "&cYou cannot afford this ability!");
        abilities.addDefault("menu.lore.status.purchased", "&cAlready purchased!");
        abilities.addDefault("menu.lore.status.unavailable", "&cYou cannot purchase this item yet!");
        abilities.addDefault("menu.lore.status.disabled", "&6Click the icon to the left to enable");
        abilities.addDefault("menu.item.status.purchase", "95:4,1", "item displayed in menu ID:DATA,AMOUNT");
        abilities.addDefault("menu.item.status.afford", "95:14,1", "item displayed in menu ID:DATA,AMOUNT");
        abilities.addDefault("menu.item.status.purchased", "95:5,1", "item displayed in menu ID:DATA,AMOUNT");
        abilities.addDefault("menu.item.status.unavailable", "95:14,1", "item displayed in menu ID:DATA,AMOUNT");
        abilities.addDefault("menu.item.status.disabled", "95:8,1", "item displayed in menu ID:DATA,AMOUNT");
        abilities.addDefault("menu.item.level", "level %number%", "Item/Ability level");
        var2.add("%level-desc%");
        var2.add("");
        var2.add("%price-format%");
        var2.add("");
        var2.add("%status-format%");
        abilities.addDefault("menu.lore.levels.enabled", var2, "Level enabled item format");
        ArrayList var3 = new ArrayList();
        var3.add("%level-desc%");
        var3.add("");
        var3.add("%disabled%");
        var3.add("%status-format%");
        abilities.addDefault("menu.lore.levels.disabled", var3, "Level disabled item format");
        String var1 = "triple_arrow";
        ArrayList var4 = new ArrayList();
        var4.add("&7Shoot 3 arrows at the same time");
        addAbilitieSection(abilities, var4, var1, "&aTriple arrow shot", "262,3");
        ArrayList var5 = new ArrayList();
        var5.add("&7Have a %chance%% chance of shooting 3 arrows");
        var5.add("&7at the same time");
        addAbilitieLevelSection(abilities, var5, var1, "1", 50, 4, false, 3);
        addAbilitieLevelSection(abilities, var5, var1, "2", 100, 6, false, 3);
        addAbilitieLevelSection(abilities, var5, var1, "3", 200, 8, false, 3);
        addAbilitieLevelSection(abilities, var5, var1, "4", 1000, 10, false, 3);
        addAbilitieLevelSection(abilities, var5, var1, "5", 2000, 12, false, 3);
        addAbilitieLevelSection(abilities, var5, var1, "6", 5000, 14, false, 3);
        addAbilitieLevelSection(abilities, var5, var1, "7", 10000, 16, false, 3);
        addAbilitieLevelSection(abilities, var5, var1, "8", 20000, 18, false, 3);
        var1 = "adrenaline_boost";
        ArrayList var6 = new ArrayList();
        var6.add("&7When you get hurt have the chance to get a speed boost");
        addAbilitieSection(abilities, var6, var1, "&aAdrenaline boost", "373,1");
        ArrayList var7 = new ArrayList();
        var7.add("&7Have a %chance%% chance of getting a speed");
        var7.add("&7boost when you get hurt");
        addAbilitieLevelSection(abilities, var7, var1, "1", 50, 4, false, 0);
        addAbilitieLevelSection(abilities, var7, var1, "2", 100, 6, false, 0);
        addAbilitieLevelSection(abilities, var7, var1, "3", 200, 8, false, 0);
        addAbilitieLevelSection(abilities, var7, var1, "4", 1000, 10, false, 0);
        addAbilitieLevelSection(abilities, var7, var1, "5", 2000, 12, false, 0);
        addAbilitieLevelSection(abilities, var7, var1, "6", 5000, 14, false, 0);
        addAbilitieLevelSection(abilities, var7, var1, "7", 10000, 16, false, 0);
        addAbilitieLevelSection(abilities, var7, var1, "8", 20000, 18, false, 0);
        var1 = "feather_weight";
        ArrayList var8 = new ArrayList();
        var8.add("&7Take less fall damage");
        addAbilitieSection(abilities, var8, var1, "&aFeather weight", "288,1");
        ArrayList var9 = new ArrayList();
        var9.add("&7Take %value%% less fall damage %chance%%");
        var9.add("&7of the time");
        addAbilitieLevelSection(abilities, var9, var1, "1", 50, 4, true, 50);
        addAbilitieLevelSection(abilities, var9, var1, "2", 100, 8, true, 50);
        addAbilitieLevelSection(abilities, var9, var1, "3", 200, 12, true, 50);
        addAbilitieLevelSection(abilities, var9, var1, "4", 1000, 16, true, 50);
        addAbilitieLevelSection(abilities, var9, var1, "5", 2000, 20, true, 50);
        addAbilitieLevelSection(abilities, var9, var1, "6", 5000, 24, true, 50);
        addAbilitieLevelSection(abilities, var9, var1, "7", 10000, 28, true, 50);
        addAbilitieLevelSection(abilities, var9, var1, "8", 20000, 32, true, 50);
        var1 = "aggressive_mode";
        ArrayList var10 = new ArrayList();
        var10.add("&7Do more damage when you have less");
        var10.add("&7than 5 hearts");
        addAbilitieSection(abilities, var10, var1, "&aAggressive mode", "267,1");
        ArrayList var11 = new ArrayList();
        var11.add("&7When you have less than 5 hearts you");
        var11.add("&7inflict %value%% more damage %chance%% of the time");
        addAbilitieLevelSection(abilities, var11, var1, "1", 50, 2, true, 50);
        addAbilitieLevelSection(abilities, var11, var1, "2", 100, 4, true, 50);
        addAbilitieLevelSection(abilities, var11, var1, "3", 200, 6, true, 50);
        addAbilitieLevelSection(abilities, var11, var1, "4", 1000, 8, true, 50);
        addAbilitieLevelSection(abilities, var11, var1, "5", 2000, 10, true, 50);
        addAbilitieLevelSection(abilities, var11, var1, "6", 5000, 12, true, 50);
        addAbilitieLevelSection(abilities, var11, var1, "7", 10000, 14, true, 50);
        addAbilitieLevelSection(abilities, var11, var1, "8", 20000, 16, true, 50);
        var1 = "arrow_tank";
        ArrayList var12 = new ArrayList();
        var12.add("&7Take less damage from arrows");
        addAbilitieSection(abilities, var12, var1, "&aArrow tank skin", "307,1");
        ArrayList var13 = new ArrayList();
        var13.add("&7Have a %chance%% chance of taking %value%%");
        var13.add("&7less projectile damage");
        addAbilitieLevelSection(abilities, var13, var1, "1", 50, 4, true, 50);
        addAbilitieLevelSection(abilities, var13, var1, "2", 100, 6, true, 50);
        addAbilitieLevelSection(abilities, var13, var1, "3", 200, 8, true, 50);
        addAbilitieLevelSection(abilities, var13, var1, "4", 1000, 10, true, 50);
        addAbilitieLevelSection(abilities, var13, var1, "5", 2000, 12, true, 50);
        addAbilitieLevelSection(abilities, var13, var1, "6", 5000, 14, true, 50);
        addAbilitieLevelSection(abilities, var13, var1, "7", 10000, 16, true, 50);
        addAbilitieLevelSection(abilities, var13, var1, "8", 20000, 18, true, 50);
        var1 = "mining_luck";
        ArrayList var14 = new ArrayList();
        var14.add("&7Mining skill is increased so you can get");
        var14.add("&7more from each ore");
        addAbilitieSection(abilities, var14, var1, "&aMining luck", "278,1");
        ArrayList var15 = new ArrayList();
        var15.add("&7Have a %chance%% chance of getting %value% of an");
        var15.add("&7resource wjem you mine and ore");
        addAbilitieLevelSection(abilities, var15, var1, "1", 25, 4, true, 2);
        addAbilitieLevelSection(abilities, var15, var1, "2", 50, 8, true, 2);
        addAbilitieLevelSection(abilities, var15, var1, "3", 100, 12, true, 2);
        addAbilitieLevelSection(abilities, var15, var1, "4", 500, 16, true, 2);
        addAbilitieLevelSection(abilities, var15, var1, "5", 1000, 20, true, 2);
        addAbilitieLevelSection(abilities, var15, var1, "6", 2500, 24, true, 2);
        addAbilitieLevelSection(abilities, var15, var1, "7", 5000, 28, true, 2);
        addAbilitieLevelSection(abilities, var15, var1, "8", 10000, 32, true, 2);
        var1 = "woodchopping_luck";
        ArrayList var16 = new ArrayList();
        var16.add("&7Woodchopping skill is increased so you can get");
        var16.add("&7more from logs from a single piece");
        addAbilitieSection(abilities, var16, var1, "&aWoodchopping luck", "279,1");
        ArrayList var17 = new ArrayList();
        var17.add("&7Have a %chance%% chance of getting %value% logs");
        addAbilitieLevelSection(abilities, var17, var1, "1", 25, 4, true, 2);
        addAbilitieLevelSection(abilities, var17, var1, "2", 50, 8, true, 2);
        addAbilitieLevelSection(abilities, var17, var1, "3", 100, 12, true, 2);
        addAbilitieLevelSection(abilities, var17, var1, "4", 500, 16, true, 2);
        addAbilitieLevelSection(abilities, var17, var1, "5", 1000, 20, true, 2);
        addAbilitieLevelSection(abilities, var17, var1, "6", 2500, 24, true, 2);
        addAbilitieLevelSection(abilities, var17, var1, "7", 5000, 28, true, 2);
        addAbilitieLevelSection(abilities, var17, var1, "8", 10000, 32, true, 2);
        var1 = "pirate";
        ArrayList var18 = new ArrayList();
        var18.add("&7Find hidden treasures in dirt");
        addAbilitieSection(abilities, var18, var1, "&aPirate", "3,1");
        ArrayList var19 = new ArrayList();
        var19.add("1 1 apple");
        var19.add("2 12 arrow");
        var19.add("2 2 egg");
        var19.add("1 1 stone_sword");
        var19.add("2 6 wood");
        var19.add("2 6 cobblestone");
        var19.add("3 6 snow_ball");
        var19.add("1 1 leather_boots");
        abilities.addDefault("abilities." + var1 + ".treasures", var19, "Possible treasure items", "Format: MIN-AMOUNT MAX-AMOUNT ITEM:DATA");
        ArrayList var20 = new ArrayList();
        var20.add("&7Find treasure in %chance%% of dirt");
        addAbilitieLevelSection(abilities, var20, var1, "1", 25, 4, false, 0);
        addAbilitieLevelSection(abilities, var20, var1, "2", 50, 6, false, 0);
        addAbilitieLevelSection(abilities, var20, var1, "3", 100, 8, false, 0);
        addAbilitieLevelSection(abilities, var20, var1, "4", 500, 10, false, 0);
        addAbilitieLevelSection(abilities, var20, var1, "5", 1000, 12, false, 0);
        addAbilitieLevelSection(abilities, var20, var1, "6", 2500, 14, false, 0);
        addAbilitieLevelSection(abilities, var20, var1, "7", 5000, 16, false, 0);
        addAbilitieLevelSection(abilities, var20, var1, "8", 10000, 18, false, 0);
        var1 = "fire_resistance";
        ArrayList var21 = new ArrayList();
        var21.add("&7Take less fire damage");
        addAbilitieSection(abilities, var21, var1, "&aFire resistance", "259,1");
        ArrayList var22 = new ArrayList();
        var22.add("&7Take %value%% less fire and lava damage");
        var22.add("&7%chance%% of the time");
        addAbilitieLevelSection(abilities, var22, var1, "1", 50, 4, true, 50);
        addAbilitieLevelSection(abilities, var22, var1, "2", 100, 8, true, 50);
        addAbilitieLevelSection(abilities, var22, var1, "3", 200, 12, true, 50);
        addAbilitieLevelSection(abilities, var22, var1, "4", 1000, 16, true, 50);
        addAbilitieLevelSection(abilities, var22, var1, "5", 2000, 20, true, 50);
        addAbilitieLevelSection(abilities, var22, var1, "6", 5000, 24, true, 50);
        addAbilitieLevelSection(abilities, var22, var1, "7", 10000, 28, true, 50);
        addAbilitieLevelSection(abilities, var22, var1, "8", 20000, 32, true, 50);
        abilities.options().copyDefaults(true);
        abilities.getEConfig().setNewLinePerKey(false);
        abilities.save();
    }

    private static void addAbilitieSection(SkyConfiguration var0, List<String> var1, String var2, String var3, String var4) {
        var0.addDefault("abilities." + var2 + ".enabled", true, "enable or disable this ability");
        var0.addDefault("abilities." + var2 + ".name", var3, "ability title/name");
        var0.addDefault("abilities." + var2 + ".desc", var1, "ability description item");
        var0.addDefault("abilities." + var2 + ".item", var4, "item displayed in menu ID:DATA,AMOUNT");
    }

    private static void addAbilitieLevelSection(SkyConfiguration var0, List<String> var1, String var2, String var3, int var4, int var5, boolean var6, int var7) {
        var0.addDefault("abilities." + var2 + ".levels_desc", var1, "levels description displayed in menu");
        var0.addDefault("abilities." + var2 + ".level." + var3 + ".price", var4, "level price");
        var0.addDefault("abilities." + var2 + ".level." + var3 + ".chance", var5, "level chance");
        if (var6) {
            var0.addDefault("abilities." + var2 + ".level." + var3 + ".value", var7, "level value");
        }

    }

    public static void shopConfig() {
        File var0 = new File(SkyWars.getPlugin().getDataFolder(), "shop.yml");
        shop = new SkyConfiguration(var0);
        if (!shop.isSet("config_version") || shop.getInt("config_version") != 1 && shop.getInt("config_version") != 2) {
            shop.setHeader("---------------------------------------------------------------- #", "", "IMPORTANT: ALL MENU NAMES (SUB MENUS AND MAIN MENU) HAVE TO BE DIFFERENT", "", "---------------------------------------------------------------- #");
            ArrayList var1 = new ArrayList();
            shop.addDefault("config_version", 2, "Don't edit this value");
            shop.addDefault("shopingame", true);
            shop.addDefault("item.enabled", false, "false (Shop menu and Item disabled), true (Shop menu and Item enabled)");
            shop.addDefault("item.inventorySlot", 1, "Slot where the item will be placed (Recommended: 0-8)");
            shop.addDefault("item.item", 340, "ID:Data or NAME:Data (If Data equals to 0 is not necessary to write it)");
            shop.addDefault("item.name", "&e&lShop", "Item name");
            var1.add("&7Click me to open the shop");
            var1.add("&7to buy lots of cool stuff for SkyWars");
            shop.addDefault("item.lore", var1, "lore: Item lore or description");
            shop.addDefault("shop_size", 6, "All Shop menu size (rows) (MAX VALUE: 6)");
            shop.addDefault("main.main_name", "&fSkyWars Shop", "main_name: Main Menu Title");
            shop.addDefault("main.items.51.item", 340, "item: ID:Data or NAME:Data");
            shop.addDefault("main.items.51.name", "&9Close menu", "name: Item Name");
            ArrayList var2 = new ArrayList();
            var2.add("&7Close the shopping");
            var2.add("&7menu.");
            shop.addDefault("main.items.51.lore", var2, "Item lore or description");
            shop.addDefault("main.items.51.action", "CLOSE", "action:", "\tCLOSE: Close menu", "\tNONE: Does nothing");
            shop.addDefault("all.49.item", 395, "ID:Data or NAME:Data");
            shop.addDefault("all.49.name", "&6Total points: &a%coins%", "name: Item Name");
            ArrayList var3 = new ArrayList();
            var3.add("&5Earn point from");
            var3.add("&5playing games");
            shop.addDefault("all.49.lore", var3, "Item lore or description");
            shop.addDefault("all.49.action", "CLOSE", "action:", "\tCLOSE: Close menu", "\tNONE: Does nothing");
            shop.addDefault("allsubmenus.50.item", 340, "ID:Data or NAME:Data");
            shop.addDefault("allsubmenus.50.name", "&9Back", "Item name");
            ArrayList var4 = new ArrayList();
            var4.add("&7Go back to the shopping menu");
            shop.addDefault("allsubmenus.50.lore", var4, "Item lore or description");
            shop.addDefault("allsubmenus.50.action", "MAIN", "action:", "\tCLOSE: Close menu", "\tNONE: Does nothing", "\tMAIN: Back to the main menu");
            byte var5 = 22;
            shop.addDefault("submenus." + var5 + ".sub_name", "&fSkyWars Kits", "Sub menu title");
            shop.addDefault("submenus." + var5 + ".item", 265, "ID:Data or NAME:Data");
            shop.addDefault("submenus." + var5 + ".name", "&eSkyWars Kits", "Item name");
            ArrayList var6 = new ArrayList();
            var6.add("&7Purchase SkyWars kits");
            shop.addDefault("submenus." + var5 + ".lore", var6, "Item lore or description");
            shop.addDefault("submenus." + var5 + ".content.11.item", "KIT,Fisherman", "Item variable: KIT,KitName (Get item, name, description and price from the kit)");
            shop.addDefault("submenus." + var5 + ".content.12.item", "KIT,Lumberjack");
            shop.addDefault("submenus." + var5 + ".content.13.item", "KIT,Spiderman");
            shop.addDefault("submenus." + var5 + ".content.14.item", "KIT,Blacksmith");
            shop.addDefault("submenus." + var5 + ".content.15.item", "KIT,Digger");
            shop.addDefault("submenus." + var5 + ".content.16.item", "KIT,Redstone_master");
            shop.addDefault("submenus." + var5 + ".content.17.item", "KIT,Farmer");
            shop.addDefault("submenus." + var5 + ".content.20.item", "KIT,Chicken");
            shop.addDefault("submenus." + var5 + ".content.21.item", "KIT,Joker");
            shop.addDefault("submenus." + var5 + ".content.22.item", "KIT,Scout");
            shop.addDefault("submenus." + var5 + ".content.23.item", "KIT,Pyromaniac");
            shop.addDefault("submenus." + var5 + ".content.24.item", "KIT,Archer");
            shop.addDefault("submenus." + var5 + ".content.25.item", "KIT,Enchanter");
            shop.addDefault("submenus." + var5 + ".content.26.item", "KIT,Enderman");
            shop.addDefault("submenus." + var5 + ".content.30.item", "KIT,Iron_golem");
            shop.addDefault("submenus." + var5 + ".content.31.item", "KIT,Healer");
            shop.addDefault("submenus." + var5 + ".content.32.item", "KIT,Bomber");
            shop.addDefault("submenus." + var5 + ".content.33.item", "KIT,Swordsman");
            shop.addDefault("submenu.abilities.enabled", true, "Enable or disable Abilities in shop menu");
            shop.addDefault("submenu.abilities.name", "&fSkyWars Abilities - Page %number%", "Abilities submenu name");
            shop.addDefault("submenu.abilities.slot", 24, "Abilities main menu item slot");
            shop.addDefault("submenu.abilities.item.name", "&eSkyWars Abilities", "Abilities item name");
            shop.addDefault("submenu.abilities.item.item", 301, "Abilities item");
            ArrayList var7 = new ArrayList();
            var7.add("&7Purchase SkyWars abilities");
            shop.addDefault("submenu.abilities.item.lore", var7, "Abilities item description");
            shop.addDefault("submenu.abilities.next.item", 338, "Abilities next page item");
            shop.addDefault("submenu.abilities.next.name", "&6Next page", "Abilities next page item name");
            shop.addDefault("submenu.abilities.next.slot", 54, "Abilities next page item slot");
            shop.addDefault("submenu.abilities.previous.item", 338, "Abilities previous page item");
            shop.addDefault("submenu.abilities.previous.name", "&6Previous page", "Abilities previous page item name");
            shop.addDefault("submenu.abilities.previous.slot", 46, "Abilities previous page item slot");
            shop.options().copyDefaults(true);
            shop.getEConfig().setNewLinePerKey(true);
            shop.save();
        }
    }

    public static void signsConfig() {
        File file = new File(SkyWars.getPlugin().getDataFolder(), "signs.yml");
        signs = new SkyConfiguration(file);
        signs.setHeader("SIGNS CONFIGURATION");
        signs.addDefault("rotation", false, "Enable or disable rotation system (disabled by default)", "If rotation is enabled the sign will select a random arena available, that means that your server can have 30 arenas and only 10 signs", "and all arenas can be played without have one sign per arena");
        signs.addDefault("rotationDelay", 60, "Delay in ticks (20 Ticks = 1 Second) when the sign will search another game after being in-game (Only if rotation is enable)");
        signs.addDefault("change_block", true, "Enable or disable the change of the block depending of the arena state");
        ArrayList var1 = Lists.newArrayList("&lSkyWars", "%state%", "&nMap: %map%", "&8%players%/%maxplayers%");
        signs.addDefault("format.game", var1);
        ArrayList var2 = Lists.newArrayList("&l----------", "SEARCHING", "GAMES", "&l----------");
        signs.addDefault("format.searching", var2);
        signs.addDefault("state", "", "The block that will be placed on the wall depending of the arena state (change_block must be enabled)", "Block Format: ITEM_NAME:DATA (If DATA is 0 you don't have to type it)");
        signs.addDefault("state.waiting", "STAINED_GLASS:5");
        signs.addDefault("state.starting", "STAINED_GLASS:4");
        signs.addDefault("state.full", "STAINED_GLASS:10");
        signs.addDefault("state.ingame", "STAINED_GLASS:14");
        signs.addDefault("state.searching", "STAINED_GLASS");
        signs.addDefault("signs", new ArrayList<>());
        signs.options().copyDefaults(true);
        signs.getEConfig().setNewLinePerKey(true);

        for (String var4 : signs.getConfigurationSection("state").getKeys(false)) {
            String var5 = signs.getString("state." + var4);
            signs.set("state." + var4, Utils.readItem(var5).toString());
        }

        signs.save();
    }

    public static void databaseConfig() {
        File file = new File(SkyWars.getPlugin().getDataFolder(), "database.yml");
        database = new SkyConfiguration(file);
        database.setHeader("DATABASE CONFIGURATION");

        database.addDefault("type", "SQLite", "Database engine: SQLite or MySQL");
        database.addDefault("sqlite.path", "plugins/SkyWars/Database.db", "SQLite database file path relative to server root");

        database.addDefault("mysql.host", "localhost", "MySQL server host");
        database.addDefault("mysql.port", 3306, "MySQL server port");
        database.addDefault("mysql.database", "SkyWars", "MySQL database name");
        database.addDefault("mysql.user", "root", "MySQL user");
        database.addDefault("mysql.password", "CHANGEME", "MySQL password (DO NOT COMMIT REAL CREDENTIALS)");
        database.addDefault("mysql.useLog4Jdbc", false, "Use log4jdbc for debugging (optional)");
        database.addDefault("mysql.pool.maxPoolSize", 8, "HikariCP max pool size");
        database.addDefault("mysql.pool.minimumIdle", 1, "HikariCP minimum idle");
        database.addDefault("mysql.pool.maxLifetimeMs", 180000, "HikariCP max lifetime ms");

        database.addDefault("tables.data", "SkyWars_Data", "Table name for player data");
        database.addDefault("tables.economy", "SkyWars_Economy", "Table name for economy data");
        database.addDefault("tables.servers", "SkyWars_Servers", "Table name for servers info");

        database.addDefault("debug.debug-database", false, "Enable debug for database operations");

        database.addDefault("nats.url", "nats://127.0.0.1:4222", "NATS server URL used for instance/proxy messaging");

        database.options().copyDefaults(true);
        database.getEConfig().setNewLinePerKey(true);
        database.save();
    }
}
